#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from q4.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "q4.y"

    #include <stdio.h>
    #include <string.h>
    #include <stdlib.h>
    void yyerror(char *);
    int yylex(void);

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IF	258
#define	ELSE	259
#define	FOR	260
#define	INT	261
#define	CHAR	262
#define	DOUBLE	263
#define	VOID	264
#define	WHILE	265
#define	CONTINUE	266
#define	BREAK	267
#define	RETURN	268
#define	LP	269
#define	RP	270
#define	LB	271
#define	RB	272
#define	LSB	273
#define	RSB	274
#define	DBQUOTE	275
#define	SNQUOTE	276
#define	RELOP	277
#define	LOGOP	278
#define	ASGNOP	279
#define	ADD	280
#define	MINUS	281
#define	DIV	282
#define	STAR	283
#define	PERCNT	284
#define	NOT	285
#define	AMPRESAND	286
#define	SMCOL	287
#define	IDENT	288
#define	NUM	289
#define	STRING	290
#define	CHARLITERAL	291
#define	COMA	292
#define	INCOP	293
#define	EQL	294
#define	END_OF_FILE	295


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IF;
static const int ELSE;
static const int FOR;
static const int INT;
static const int CHAR;
static const int DOUBLE;
static const int VOID;
static const int WHILE;
static const int CONTINUE;
static const int BREAK;
static const int RETURN;
static const int LP;
static const int RP;
static const int LB;
static const int RB;
static const int LSB;
static const int RSB;
static const int DBQUOTE;
static const int SNQUOTE;
static const int RELOP;
static const int LOGOP;
static const int ASGNOP;
static const int ADD;
static const int MINUS;
static const int DIV;
static const int STAR;
static const int PERCNT;
static const int NOT;
static const int AMPRESAND;
static const int SMCOL;
static const int IDENT;
static const int NUM;
static const int STRING;
static const int CHARLITERAL;
static const int COMA;
static const int INCOP;
static const int EQL;
static const int END_OF_FILE;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IF=258
	,ELSE=259
	,FOR=260
	,INT=261
	,CHAR=262
	,DOUBLE=263
	,VOID=264
	,WHILE=265
	,CONTINUE=266
	,BREAK=267
	,RETURN=268
	,LP=269
	,RP=270
	,LB=271
	,RB=272
	,LSB=273
	,RSB=274
	,DBQUOTE=275
	,SNQUOTE=276
	,RELOP=277
	,LOGOP=278
	,ASGNOP=279
	,ADD=280
	,MINUS=281
	,DIV=282
	,STAR=283
	,PERCNT=284
	,NOT=285
	,AMPRESAND=286
	,SMCOL=287
	,IDENT=288
	,NUM=289
	,STRING=290
	,CHARLITERAL=291
	,COMA=292
	,INCOP=293
	,EQL=294
	,END_OF_FILE=295


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IF=258;
const int YY_parse_CLASS::ELSE=259;
const int YY_parse_CLASS::FOR=260;
const int YY_parse_CLASS::INT=261;
const int YY_parse_CLASS::CHAR=262;
const int YY_parse_CLASS::DOUBLE=263;
const int YY_parse_CLASS::VOID=264;
const int YY_parse_CLASS::WHILE=265;
const int YY_parse_CLASS::CONTINUE=266;
const int YY_parse_CLASS::BREAK=267;
const int YY_parse_CLASS::RETURN=268;
const int YY_parse_CLASS::LP=269;
const int YY_parse_CLASS::RP=270;
const int YY_parse_CLASS::LB=271;
const int YY_parse_CLASS::RB=272;
const int YY_parse_CLASS::LSB=273;
const int YY_parse_CLASS::RSB=274;
const int YY_parse_CLASS::DBQUOTE=275;
const int YY_parse_CLASS::SNQUOTE=276;
const int YY_parse_CLASS::RELOP=277;
const int YY_parse_CLASS::LOGOP=278;
const int YY_parse_CLASS::ASGNOP=279;
const int YY_parse_CLASS::ADD=280;
const int YY_parse_CLASS::MINUS=281;
const int YY_parse_CLASS::DIV=282;
const int YY_parse_CLASS::STAR=283;
const int YY_parse_CLASS::PERCNT=284;
const int YY_parse_CLASS::NOT=285;
const int YY_parse_CLASS::AMPRESAND=286;
const int YY_parse_CLASS::SMCOL=287;
const int YY_parse_CLASS::IDENT=288;
const int YY_parse_CLASS::NUM=289;
const int YY_parse_CLASS::STRING=290;
const int YY_parse_CLASS::CHARLITERAL=291;
const int YY_parse_CLASS::COMA=292;
const int YY_parse_CLASS::INCOP=293;
const int YY_parse_CLASS::EQL=294;
const int YY_parse_CLASS::END_OF_FILE=295;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		135
#define	YYFLAG		-32768
#define	YYNTBASE	41

#define YYTRANSLATE(x) ((unsigned)(x) <= 295 ? yytranslate[x] : 63)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     5,     7,     9,    11,    13,    15,    18,    19,
    23,    30,    39,    47,    55,    62,    66,    72,    77,    78,
    81,    86,    92,    96,    99,   103,   106,   111,   117,   119,
   122,   125,   130,   136,   138,   140,   142,   144,   146,   148,
   150,   156,   161,   167,   171,   174,   180,   188,   196,   198,
   201,   205,   209,   211,   213,   217,   221,   223,   226,   230,
   234,   236,   238,   240,   244,   247,   250,   253,   256,   259,
   262,   264,   266,   268,   270,   272,   274,   276,   278,   280,
   282
};

static const short yyrhs[] = {    42,
    15,     0,    57,     0,    57,     0,    52,     0,    47,     0,
     0,     0,    40,     0,    15,    44,     0,     0,    44,    43,
    42,     0,    51,    33,    18,    45,    19,    32,     0,    51,
    33,    18,    46,    19,    14,    52,    15,     0,    51,    33,
    18,    46,    19,    14,    15,     0,    51,    33,    18,    46,
    19,    14,    52,     0,    51,    33,    18,    46,    19,    14,
     0,    37,    51,    33,     0,    37,    51,    33,    16,    17,
     0,    45,    37,    51,    33,     0,     0,    51,    33,     0,
    51,    33,    16,    17,     0,    51,    33,    16,    17,    45,
     0,    51,    33,    45,     0,    48,    32,     0,    48,    49,
    32,     0,    51,    33,     0,    51,    33,    39,    60,     0,
    51,    33,    16,    60,    17,     0,    50,     0,    50,    49,
     0,    37,    33,     0,    37,    33,    39,    60,     0,    37,
    33,    16,    60,    17,     0,     6,     0,     7,     0,     8,
     0,     9,     0,    53,     0,    47,     0,    54,     0,    10,
    18,    58,    19,    52,     0,    33,    62,    57,    32,     0,
     5,    18,    55,    19,    52,     0,    14,    56,    15,     0,
    14,    15,     0,     3,    18,    58,    19,    52,     0,     3,
    18,    58,    19,    52,     4,    52,     0,    33,    39,    57,
    32,    58,    32,    57,     0,    52,     0,    52,    56,     0,
    60,    61,    60,     0,    57,    61,    60,     0,    60,     0,
    58,     0,    60,    23,    60,     0,    60,    22,    60,     0,
    59,     0,    58,    59,     0,    58,    23,    60,     0,    58,
    22,    60,     0,    33,     0,    34,     0,    35,     0,    18,
    57,    19,     0,    28,    60,     0,    26,    60,     0,    30,
    60,     0,    31,    60,     0,    60,    38,     0,    38,    60,
     0,    25,     0,    26,     0,    30,     0,    31,     0,    25,
     0,    26,     0,    28,     0,    27,     0,    29,     0,    24,
     0,    39,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    23,    24,    27,    28,    29,    30,    31,    34,    35,    35,
    38,    41,    42,    46,    47,    52,    53,    54,    57,    58,
    59,    60,    61,    65,    66,    69,    70,    71,    74,    75,
    78,    79,    80,    83,    84,    85,    86,    89,    90,    91,
    92,    93,    94,    97,    98,   101,   102,   105,   108,   109,
   112,   113,   114,   115,   119,   120,   121,   124,   125,   126,
   130,   131,   132,   133,   134,   135,   136,   137,   138,   139,
   142,   143,   144,   145,   148,   149,   150,   151,   152,   155,
   156
};

static const char * const yytname[] = {   "$","error","$illegal.","IF","ELSE",
"FOR","INT","CHAR","DOUBLE","VOID","WHILE","CONTINUE","BREAK","RETURN","LP",
"RP","LB","RB","LSB","RSB","DBQUOTE","SNQUOTE","RELOP","LOGOP","ASGNOP","ADD",
"MINUS","DIV","STAR","PERCNT","NOT","AMPRESAND","SMCOL","IDENT","NUM","STRING",
"CHARLITERAL","COMA","INCOP","EQL","END_OF_FILE","st","function_star","@1","function_h",
"arg_decl_star","arg_decl","declaration","declaration_type","multiple_decl_star",
"multiple_decl","type","statement","block_statement","if_stmnt","for_expr","multiple_statement",
"expr","rel_expr","rel_expr_star","primary_expr","binary_op","assgn_op","primary_expr"
};
#endif

static const short yyr1[] = {     0,
    41,    41,    -1,    -1,    -1,    -1,    -1,    42,    43,    42,
    -1,    -1,    -1,    44,    44,    45,    45,    45,    46,    46,
    46,    46,    46,    47,    47,    48,    48,    48,    49,    49,
    50,    50,    50,    51,    51,    51,    51,    52,    52,    52,
    52,    52,    52,    53,    53,    54,    54,    55,    56,    56,
    57,    57,    57,    57,    58,    58,    58,    59,    59,    59,
    60,    60,    60,    60,    60,    60,    60,    60,    60,    60,
    -1,    -1,    -1,    -1,    61,    61,    61,    61,    61,    62,
    62
};

static const short yyr2[] = {     0,
     2,     1,     1,     1,     1,     1,     1,     2,     0,     3,
     6,     8,     7,     7,     6,     3,     5,     4,     0,     2,
     4,     5,     3,     2,     3,     2,     4,     5,     1,     2,
     2,     4,     5,     1,     1,     1,     1,     1,     1,     1,
     5,     4,     5,     3,     2,     5,     7,     7,     1,     2,
     3,     3,     1,     1,     3,     3,     1,     2,     3,     3,
     1,     1,     1,     3,     2,     2,     2,     2,     2,     2,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     1
};

static const short yydefact[] = {     0,
    34,    35,    36,    37,     0,     0,     0,     0,     0,     0,
    61,    62,    63,     0,     0,     9,     0,     2,    54,    57,
    53,     8,     0,    66,    65,    67,    68,    70,     1,     0,
     0,    75,    76,    78,    77,    79,     0,     0,     0,     0,
    57,     0,     0,     0,    69,     0,    64,    10,    19,    52,
    60,    59,    56,    55,    51,     0,     0,     0,    20,    15,
     0,     0,    23,     0,     0,     0,     0,     0,    39,     0,
     0,    14,    38,    40,    21,     0,     0,     0,     0,     0,
    45,    49,     0,    80,    81,     0,    24,     0,     0,    29,
    26,    22,    16,     0,     0,     0,     0,     0,    50,    44,
     0,    31,    25,    30,     0,     0,     0,    18,     0,     0,
     0,     0,    42,     0,     0,     0,    27,    17,    46,     0,
    43,    41,     0,    32,    28,     0,     0,    33,    47,     0,
     0,    48,     0,     0,     0
};

static const short yydefgoto[] = {   133,
    15,    30,    16,    63,    56,    69,    70,    89,    90,    71,
    82,    73,    74,    97,    83,    18,    19,    20,    42,    37,
    86
};

static const short yypact[] = {   111,
-32768,-32768,-32768,-32768,   116,   190,   190,   190,   190,   190,
-32768,-32768,-32768,   190,    -2,-32768,   -14,   107,   179,-32768,
   204,-32768,   218,   -23,   -23,   -23,   -23,   -23,-32768,   242,
     7,-32768,-32768,-32768,-32768,-32768,   190,   190,   190,   179,
    40,    10,   190,   190,-32768,   190,-32768,-32768,   116,   -23,
   -23,   -23,   -23,   -23,   -23,    32,    16,    38,    29,    88,
    41,   116,    20,    45,    46,    55,    21,   -19,-32768,   -16,
    42,-32768,-32768,-32768,    39,    49,   116,   190,    51,   190,
-32768,    88,    64,-32768,-32768,   190,-32768,    52,    56,    50,
    -5,    20,    74,    59,   129,    60,    81,   147,-32768,-32768,
   227,     2,-32768,-32768,   190,   190,    84,-32768,    88,   190,
    88,    88,-32768,   190,   190,    30,   -23,-32768,    99,   235,
-32768,-32768,    33,   -23,-32768,    88,   190,-32768,-32768,   161,
   190,   107,   104,   108,-32768
};

static const short yypgoto[] = {-32768,
    86,-32768,   106,    63,-32768,-32768,-32768,    37,-32768,    12,
   -56,-32768,-32768,-32768,    48,    -3,   -18,   -17,     0,   119,
-32768
};


#define	YYLAST		267


static const short yytable[] = {    21,
    40,    41,    23,    72,    84,    21,    24,    25,    26,    27,
   105,    17,    29,    28,    45,    87,    17,   114,    31,    85,
    88,    40,    41,    64,    49,    65,     1,     2,     3,     4,
    66,    43,    44,   106,    67,    81,    50,    51,    52,   -58,
   115,    17,    53,    54,    61,    55,   125,    45,    59,   128,
    58,    60,   119,    68,   121,   122,    77,    75,   -58,    95,
    57,    98,    78,    79,   -58,    62,   -58,    45,   -58,   129,
    45,   -58,    80,    76,    91,    62,    40,    41,   100,    40,
    41,    93,   101,    96,   102,    21,    88,   103,    94,   107,
    64,   108,    65,     1,     2,     3,     4,    66,   110,   111,
   118,    67,   126,   134,   116,   117,   120,   135,   130,    21,
    22,    40,    41,   123,   124,    48,     1,     2,     3,     4,
    68,     1,     2,     3,     4,     5,   104,   132,     6,    99,
    21,    32,    33,    34,    35,    36,     7,    92,     8,    46,
     9,    10,     0,    11,    12,    13,     6,   109,    14,     0,
    38,    39,     0,     0,     7,     0,     8,     0,     9,    10,
     0,    11,    12,    13,     6,   112,    14,     0,    38,    39,
     0,     0,     7,     0,     8,     0,     9,    10,     6,    11,
    12,    13,    38,    39,    14,     0,     7,     0,     8,     0,
     9,    10,   131,    11,    12,    13,     6,     0,    14,     0,
    38,    39,     0,     0,     7,     0,     8,     6,     9,    10,
     0,    11,    12,    13,     0,     7,    14,     8,     0,     9,
    10,     0,    11,    12,    13,    43,    44,    14,    32,    33,
    34,    35,    36,     0,     0,     0,    47,     0,     0,     0,
     0,    45,    32,    33,    34,    35,    36,     1,     2,     3,
     4,    32,    33,    34,    35,    36,     5,     0,   113,    32,
    33,    34,    35,    36,     0,     0,   127
};

static const short yycheck[] = {     0,
    19,    19,     6,    60,    24,     6,     7,     8,     9,    10,
    16,     0,    15,    14,    38,    32,     5,    16,    33,    39,
    37,    40,    40,     3,    18,     5,     6,     7,     8,     9,
    10,    22,    23,    39,    14,    15,    37,    38,    39,     0,
    39,    30,    43,    44,    16,    46,    17,    38,    33,    17,
    19,    14,   109,    33,   111,   112,    37,    17,    19,    78,
    49,    80,    18,    18,    25,    37,    27,    38,    29,   126,
    38,    32,    18,    62,    33,    37,    95,    95,    15,    98,
    98,    33,    86,    33,    33,    86,    37,    32,    77,    16,
     3,    33,     5,     6,     7,     8,     9,    10,    39,    19,
    17,    14,     4,     0,   105,   106,   110,     0,   127,   110,
     5,   130,   130,   114,   115,    30,     6,     7,     8,     9,
    33,     6,     7,     8,     9,    15,    90,   131,    18,    82,
   131,    25,    26,    27,    28,    29,    26,    75,    28,    21,
    30,    31,    -1,    33,    34,    35,    18,    19,    38,    -1,
    22,    23,    -1,    -1,    26,    -1,    28,    -1,    30,    31,
    -1,    33,    34,    35,    18,    19,    38,    -1,    22,    23,
    -1,    -1,    26,    -1,    28,    -1,    30,    31,    18,    33,
    34,    35,    22,    23,    38,    -1,    26,    -1,    28,    -1,
    30,    31,    32,    33,    34,    35,    18,    -1,    38,    -1,
    22,    23,    -1,    -1,    26,    -1,    28,    18,    30,    31,
    -1,    33,    34,    35,    -1,    26,    38,    28,    -1,    30,
    31,    -1,    33,    34,    35,    22,    23,    38,    25,    26,
    27,    28,    29,    -1,    -1,    -1,    19,    -1,    -1,    -1,
    -1,    38,    25,    26,    27,    28,    29,     6,     7,     8,
     9,    25,    26,    27,    28,    29,    15,    -1,    32,    25,
    26,    27,    28,    29,    -1,    -1,    32
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 23 "q4.y"
{printf("mul\n");exit(0);;
    break;}
case 3:
#line 27 "q4.y"
{printf("expr\n");exit(0);;
    break;}
case 4:
#line 28 "q4.y"
{printf("statement\n");exit(0);;
    break;}
case 5:
#line 29 "q4.y"
{printf("declaration\n");exit(0);;
    break;}
case 6:
#line 30 "q4.y"
{printf("unaryop\n");exit(0);;
    break;}
case 7:
#line 31 "q4.y"
{printf("eof\n");exit(0);;
    break;}
case 8:
#line 34 "q4.y"
{printf("empty\n");;
    break;}
case 9:
#line 35 "q4.y"
{printf("fn2\n");;
    break;}
case 10:
#line 35 "q4.y"
{printf("fnstar\n");;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 159 "q4.y"


void yyerror(char *s) {
    fprintf(stderr, "%s\n", s);
    printf("Error : %s \n",s);
    exit(0);
}

int main(void) {
    yyparse();
    return 0;
}
